name: Java CI Build

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Set up JDK 17
      uses: actions/setup-java@v3.5.0
      with:
        java-version: 17
        distribution: zulu

    # Determine next version to build. New version is in variable new_tag. Only for main branch as dependabot pull requests cannot create tags:
    # https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
    - name: Determine new version
      if: github.ref == 'refs/heads/main'
      id: versioning
      uses: anothrNick/github-tag-action@1.40.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: kevinferrare
        RELEASE_BRANCHES: main
        INITIAL_VERSION: 1.0.0
        DRY_RUN: false

    # Setup github maven for spice86 dependency read (need a different entry in settings.xml for that ...)
    # Need a token that is not GITHUB_TOKEN for dependabot
    - name: Setup custom settings.xml
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        output_file: ./spice86-maven-settings.xml
        servers: '[{ "id": "github-spice86", "username": "kevinferrare", "password": "${{secrets.GITHUB_TOKEN}}" }]'

    # Sets the versions in the pom so that the generated artifacts are not -SNAPSHOT, build and publish
    - name: Build Maven and deploy
      if: github.ref == 'refs/heads/main'
      env:
        VERSION: ${{ steps.versioning.outputs.new_tag }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mvn -B --settings ./spice86-maven-settings.xml versions:set -DnewVersion=${VERSION} &> /dev/null
        mvn -B --settings ./spice86-maven-settings.xml clean install
        mvn -B deploy

    # When on a branch, do not deploy since no tag has been created
    - name: Build Maven without deploy
      if: github.ref != 'refs/heads/main'
      run: |
        mvn -B --settings ./spice86-maven-settings.xml clean verify